### ISSUE TITLE
CI GHA Matrix: Add integration testing against more versions of ClickHouse

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.clickhouse#20]
##### SUMMARY

It makes sense to test against the oldest LTS version and maybe against the newest LTS.

Related files:
- https://github.com/ansible-collections/community.clickhouse/blob/main/.github/workflows/ansible-test-plugins.yml
- https://github.com/ansible-collections/community.clickhouse/blob/main/tests/integration/targets/setup_clickhouse/vars/main.yml

One possible solution is to update the vars file in the GHA matrix using `sed` before running the target. The versions to put in the file will be specified in GHA matrix as well.

**Comment by aleksvagachev** [comment]
@Andersson007 Hi. I'm ready to take it. I'll try to do it by the weekend.

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.clickhouse/pull/22
