### ISSUE TITLE
Add server version to the test jobs output

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.clickhouse#24]
##### SUMMARY
Add server version to the test jobs output
Currently it's not possible to differentiate between the versions:

![Screenshot from 2024-02-09 10-34-19](https://github.com/ansible-collections/community.clickhouse/assets/34477873/627b97d3-8c53-44f4-bb56-5bf56ce4181a)

**Comment by Andersson007** [comment]
cc @aleksvagachev would you like to pick it up?

**Comment by aleksvagachev** [comment]
@Andersson007 I'll do it. Can you tell me how to achieve complete completion of all tests? I can't figure out what the problem is in codecov/project.
