### ISSUE TITLE
GHA: add LTS 

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.clickhouse#89]
##### SUMMARY
1. Add 24.8.6.70 to `.github/workflows/ansible-test-plugins.yml` and `tests/integration/targets/setup_clickhouse/vars/main.yml`
2. Test locally with `ansible-test integration clickhouse_info --docker ubuntu2204 -vvv`
3. Fix
4. Push it here

I tried to do it in https://github.com/ansible-collections/community.clickhouse/pull/88
but the service refused to start complaining about some unit configuration issues.

help wanted

**Comment by aleksvagachev** [comment]
@Andersson007 I will take up this issue.
